# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6fbfdb261ed145e015d0d40d56937728f9dfedf8fd056d68aab48e3c0c7c563691b8057845eed93bdc1531a67346e05d9022fd40ef417cfbdf463f71f66a9d04
  soffice_path: /Users/dh/Applications/LibreOffice.app/Contents/MacOS/soffice

test:
  secret_key_base: d3b2d5d4a96a5fc9a467f36ddf354e78667e4ba77523a433018b161ac49a0505a3ccfef8db063cb09032099d52e4615d31eb7646e1c3886c8b4745dedef81a9f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  soffice_path: <%= ENV["SOFFICE_PATH"] %>
